AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ServerlessFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          TABLE_NAME: !Ref ServerlessTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  ServerlessTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: serverless-webapp-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
